// export const type = {
//   ADD_TO_BASKET: "ADD_TO_BASKET",
//   REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
//   INCREASE_QTY: "INCREASE_QTY",
//   DECREASE_QTY: "DECREASE_QTY",
//   SET_USER: "SET_USER",
// };

export const type = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",

  SET_USER: "SET_USER",
  SET_TOKEN: "SET_TOKEN",
  EMPTY_BASKET: "EMPTY_BASKET",
};